# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec16ece85dd6976077a89a0d44edd8bda9cf97b6bb2487863d012da8bc41bf4d8a58a1fa3baa3fadf46683d2b1db12fea0366f341f5f15130383f6481a4fa6f8

test:
  secret_key_base: 33c80342da14c74a36cefc263a6a59d83289b03750014996c2d6011226695ee21ab2190fbea85c0eabbde6eed1eb04cda3d065f7aa592ee00761ab531fdb75e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
