# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee39d53ebeda37d74d598a4426045f2d3daa42a323159fe466034d70e64d5ba46e0fdf97145cab3167ac2eed9ebb612d7c0f65bac5d60107d8f2706d0e0fac8

test:
  secret_key_base: 42e3a15295b31ad613c086c371d79af4e65bab1cb9cda1fc90a5c701ebfa66e6f9ad34250fb5fa3311c77663f400cef5a1211ba1115d61e2d5a2c19ca96edf69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
